//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;VisualPlus-Theme&gt;
        ///    &lt;Information&gt;
        ///        &lt;Name&gt;Enigma&lt;/Name&gt;
        ///        &lt;Author&gt;DarkByte7&lt;/Author&gt;
        ///    &lt;/Information&gt;
        ///    &lt;StyleTable&gt;
        ///        &lt;Shared&gt;
        ///            &lt;MainColor&gt;#ffC40D&lt;/MainColor&gt;
        ///            &lt;LightText&gt;#FF808080&lt;/LightText&gt;
        ///            &lt;Line&gt;#FFE0DEDC&lt;/Line&gt;
        ///            &lt;Shadow&gt;#FFFAF9F9&lt;/Shadow&gt;
        ///            &lt;Background&gt;
        ///                &lt;Type1&gt;#FFDCDCDC&lt;/Type1&gt;
        ///                &lt;Type2&gt;#FFDCDCDC&lt;/Type2&gt;
        ///                &lt;Type3&gt;#FF424041&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enigma {
            get {
                return ResourceManager.GetString("Enigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;VisualPlus-Theme&gt;
        ///    &lt;Information&gt;
        ///        &lt;Name&gt;Visual&lt;/Name&gt;
        ///        &lt;Author&gt;DarkByte7&lt;/Author&gt;
        ///    &lt;/Information&gt;
        ///    &lt;StyleTable&gt;
        ///        &lt;Shared&gt;
        ///            &lt;MainColor&gt;#FFC40D&lt;/MainColor&gt;
        ///            &lt;LightText&gt;#FF808080&lt;/LightText&gt;
        ///            &lt;Line&gt;#FFE0DEDC&lt;/Line&gt;
        ///            &lt;Shadow&gt;#FFFAF9F9&lt;/Shadow&gt;
        ///            &lt;Background&gt;
        ///                &lt;Type1&gt;#FFDCDCDC&lt;/Type1&gt;
        ///                &lt;Type2&gt;#FFDCDCDC&lt;/Type2&gt;
        ///                &lt;Type3&gt;#FF424041&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VisualLabel {
            get {
                object obj = ResourceManager.GetObject("VisualLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VisualPlus {
            get {
                object obj = ResourceManager.GetObject("VisualPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
